[project]
name = "ollama-client"
version = "0.1.0"
description = "Phi-4 LLM interaction skill via Ollama API"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.31.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
