[project]
name = "chroma-client"
version = "0.1.0"
description = "ChromaDB vector database client skill"
requires-python = ">=3.8"
dependencies = [
    "chromadb>=0.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
